Sprint 6 solution
Pavlusi/java-kanban pull request #4
Opened 2024-05-10 21:04 UTC by Pavlusi

2024-05-11 17:47 UTC, ErkinKasymaliev requested changes
привет, неплохая работа!
оставил коммент

2024-05-11 17:47 UTC, ErkinKasymaliev commented on src/Main.java
> +
хорошо вы удалили, но где проверка?

2024-05-11 18:37 UTC, ErkinKasymaliev requested changes

2024-05-11 18:37 UTC, ErkinKasymaliev commented on src/Main.java
> +        System.out.println(taskManager.getSubtaskList());
надо проверять историю

```
Создайте две задачи, эпик с тремя подзадачами и эпик без подзадач.
Запросите созданные задачи несколько раз в разном порядке.
После каждого запроса выведите историю и убедитесь, что в ней нет повторов.
Удалите задачу, которая есть в истории, и проверьте, что при печати она не будет выводиться.
Удалите эпик с тремя подзадачами и убедитесь, что из истории удалился как сам эпик, так и все его подзадачи.

```

2024-05-12 13:59 UTC, Pavlusi commented on src/Main.java
> +        System.out.println(taskManager.getSubtaskList());
Этот метод Майн написан в 4 спринте. Для этого спринта я не выполнял дополнительное задание.

2024-05-13 05:56 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2024-05-23 16:16 UTC, merged