Звдания 8 спритна
Pavlusi/java-kanban pull request #8
Opened 2024-08-08 14:03 UTC by Pavlusi

2024-08-09 12:12 UTC, ErkinKasymaliev requested changes
привет,  оставил комменты

2024-08-09 12:12 UTC, ErkinKasymaliev commented on src/service/InMemoryTaskManager.java
> +        if (isTasksTimeCross(task)) {
так красивее, без лишнего else:
```
@Override
public Task saveTask(Task task) {
    if (isTasksTimeCross(task)) {
       throw new TaskTimeCrossException("Задача " + task.getName() + " пересекается по времени с другой задачей");
    }
    task.setId(generateId());
    allTasks.put(task.getId(), task);
    prioritizedTasks.add(task);
    return task;
}
```
поправьте в других местах тоже

2024-08-09 12:12 UTC, ErkinKasymaliev commented on src/service/InMemoryTaskManager.java
> +    private void checkEpicTime(Epic epic) {
checkAndSetEpicTime

2024-08-09 12:12 UTC, ErkinKasymaliev commented on src/service/InMemoryTaskManager.java
> +        for (Task t : prioritizedTasks) {
тут надо использовать forEach от Stream api

2024-08-09 12:12 UTC, ErkinKasymaliev commented on test/service/InMemoryTaskManagerTest.java
> +
лишние строки

2024-08-09 20:04 UTC, Pavlusi commented on test/service/InMemoryTaskManagerTest.java
> +
не понял почему они лишние, есть один тест метода менеджера , внутри несколько приватных методов что тестируют разные сценарии работы этого метода менеджера.

2024-08-09 20:34 UTC, Pavlusi commented on src/model/Task.java
> +        this.duration = Duration.ofMinutes(10);
Дефолтное время, если пользователь не задал длительность задачи.

2024-08-10 11:36 UTC, ErkinKasymaliev commented on test/service/InMemoryTaskManagerTest.java
> +
лишние пустые строки)

2024-08-10 11:38 UTC, ErkinKasymaliev approved these changes
[привет, работа принята](https://github.com/Pavlusi/java-kanban/pull/8)

2024-08-10 19:10 UTC, merged